"""phase 6 replies

Revision ID: 80f12d01ae19
Revises: 5dd0a4f2a631
Create Date: 2026-07-23 05:00:23.246771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80f12d01ae19"
down_revision: Union[str, Sequence[str], None] = "5dd0a4f2a631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "replies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("gmail_message_id", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=True),
        sa.Column("from_address", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reply_type",
            sa.Enum("REJECTION", "INTERVIEW", "NO_REPLY", name="replytype", native_enum=False),
            nullable=True,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_replies_application_id"), "replies", ["application_id"], unique=False)
    op.create_index(
        op.f("ix_replies_gmail_message_id"), "replies", ["gmail_message_id"], unique=True
    )
    op.create_index(op.f("ix_replies_thread_id"), "replies", ["thread_id"], unique=False)
    op.add_column("applications", sa.Column("thread_id", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_applications_thread_id"), "applications", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_thread_id"), table_name="applications")
    op.drop_column("applications", "thread_id")
    op.drop_index(op.f("ix_replies_thread_id"), table_name="replies")
    op.drop_index(op.f("ix_replies_gmail_message_id"), table_name="replies")
    op.drop_index(op.f("ix_replies_application_id"), table_name="replies")
    op.drop_table("replies")
    # ### end Alembic commands ###
