"""ats boards

Revision ID: 9857afe483ee
Revises: 80f12d01ae19
Create Date: 2026-07-23 05:11:45.743735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9857afe483ee"
down_revision: Union[str, Sequence[str], None] = "80f12d01ae19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ats_boards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("GREENHOUSE", "LEVER", "ASHBY", name="atsprovider", native_enum=False),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("discovered_from", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("empty_runs", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "slug", name="uq_ats_boards_provider_slug"),
    )
    op.create_index(op.f("ix_ats_boards_provider"), "ats_boards", ["provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ats_boards_provider"), table_name="ats_boards")
    op.drop_table("ats_boards")
    # ### end Alembic commands ###
